---
# tasks file for nginx
- name: 'Install nginx package'
  apt:
    name: 'nginx={{ nginx_version }}-0ubuntu1'
    state: 'present'
    update_cache: true
  become: true

- name: 'Upload nginx config'
  template:
    src: 'nginx.conf.j2'
    dest: '/etc/nginx/sites-enabled/default'
    owner: '{{ nginx_user }}'
    group: '{{ nginx_group }}'
    mode: 0644
  become: true
  
- name: 'Ensure that nginx service is started' 
  service: 
    name: 'nginx'
    state: 'started'
    enabled: true
  become: true