---
# tasks file for wordpress
- name: 'Install required php packages'
  apt:
    name: 'unzip'
    state: 'present'
    update_cache: true
  become: true



- name: 'extract Wordpress files'
  unarchive:
    src: ' {{ wordpress_url }} '
    remote_src: true
    dest: '/opt'
    owner: '{{ wordpress_user }}'
    group: '{{ wordpress_group }}'
  become: true

- name: 'Create wordpress DB'
  mysql_db:
    name: '{{ wordpress_mysql_db_name }}'
    state: 'present'
    login_user: '{{ wordpress_mysql_login_user }}'
    login_password: '{{ wordpress_mysql_login_password }}'

- name: 'Upload  wordpress config file'
  template:
    src: 'wp-config.php.j2'
    dest: '/opt/wordpress/wp-config.php'
    owner: '{{ wordpress_user }}'
    group: '{{ wordpress_group }}'
  become: true
  notify: '{{ wordpress_nginx_handler_name }}'